notifications:
  email:
    on_success: never
    on_failure: change

dist: trusty

sudo: false

matrix:
  include:
    - os: linux

branches:
  only:
    - master
    - linux
    - /^__release-.*/

cache:
  yarn: true
  timeout: 600
  directories:
    - node_modules
    - $HOME/.electron
    - .eslintcache
    - $HOME/.cache/electron-builder

services:
  - docker

script:
  - ./script/docker/build-app.sh

after_failure:
  - yarn test:review
