notifications:
  email:
    on_success: never
    on_failure: change

dist: trusty

matrix:
  include:
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

addons:
  apt:
    packages:
      # by default the container VMs have Git 1.9.1, ermagherd...
      - git-all
      # this is required to compile keytar
      - libsecret-1-dev
      # this package is essential for testing Electron in a headless fashion
      # https://github.com/electron/electron/blob/master/docs/tutorial/testing-on-headless-ci.md
      - xvfb
      # packages required for electron-installer-debian
      - fakeroot
      - dpkg
      # packages required for electron-installer-redhat
      - rpm
      # packages required for electron-installer-appimage
      - xz-utils
      - xorriso

branches:
  only:
    - master
    - /^__release-.*/

language: node_js
node_js:
  - "7"

cache:
  timeout: 600
  directories:
    - node_modules
    - $HOME/.electron

install:
  - npm install -g npm@4.6.1
  - npm prune
  - cd app && npm prune && cd ..
  - npm install
  - npm ls --prod
  - npm ls --dev

script:
  - npm run check-prettiness
  - npm run lint
  - npm run build:prod
  - npm run test:setup
  - npm test

after_success:
  - npm run package
  - ls dist/installer

after_failure:
  - npm run test:review
