resources:
  repositories:
    - repository: self
      checkoutOptions:
        submodules: true

jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    steps:
      - script: |
          mkdir -p /tmp/local/.cache
          mkdir -p /tmp/local/.yarn
          mkdir -p /tmp/local/.node-gyp
          mkdir -p /tmp/local/.local
        displayName: 'Setup local caches'
      - script:
          docker run -u $(id -u):$(id -g) -v $(Build.SourcesDirectory):/src -v
          /tmp/local/.cache:/.cache -v /tmp/local/.yarn:/.yarn -v
          /tmp/local/.node-gyp:/.node-gyp -v /tmp/local/.local:/.local -w /src
          shiftkey/github-desktop:trusty-node-yarn-git sh -c "yarn install
          --force && yarn build:prod"
        displayName: 'Build in container'
      - script: |
          export DISPLAY=':99.0'
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          yarn test:setup && yarn test
        name: Test
      - script:
          docker run -v $(Build.SourcesDirectory):/src -v
          /tmp/local/.cache:/.cache -v /tmp/local/.yarn:/.yarn -v
          /tmp/local/.node-gyp:/.node-gyp -v /tmp/local/.local:/.local -w /src
          shiftkey/github-desktop:snapcraft-node-yarn sh -c "yarn run package"
        displayName: 'Package in Container'
        condition:
          and(succeeded(), eq(variables['Build.SourceBranch'],
          'refs/heads/linux'))
      - task: CopyFiles@2
        inputs:
          contents: |
            dist/*.yml
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
            dist/*.snap
          targetFolder: $(Build.ArtifactStagingDirectory)
          flattenFolders: true
        condition:
          and(succeeded(), eq(variables['Build.SourceBranch'],
          'refs/heads/linux'))
      - task: PublishBuildArtifacts@1
        condition:
          and(succeeded(), eq(variables['Build.SourceBranch'],
          'refs/heads/linux'))

  - job: Lint
    pool:
      vmImage: ubuntu-16.04
    steps:
      - script: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libsecret-1-dev
      - task: NodeTool@0
        inputs:
          versionSpec: '8.11.1'
      - task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
        inputs:
          versionSpec: '1.5.1'
      - script: |
          yarn install --force
        name: Install
      - script: |
          yarn lint
        name: Lint
